inherit_from:
  - ../.rubocop.yml 

# Let's relax this cop to allow long RSpec 'describe', 'it' blocks
Metrics/BlockLength:
  Max: 900
  CountComments: false
  
# Avoid modules longer than 900 lines of code 
Metrics/ModuleLength:
  CountComments: false
  Max: 900